language: cpp
sudo: required

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-6
                      - libcppunit-dev
          env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" 

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - libcppunit-dev
          env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" 

        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
                      - libcppunit-dev
          env:
            - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" 

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - wget https://www.auto.tuwien.ac.at/~mkoegler/debian/pool/main/p/pthsem/pthsem_2.0.8.tar.gz
    - tar -zxf pthsem_2.0.8.tar.gz
    - cd pthsem-2.0.8
    - ./configure && make && sudo make install
    - cd ..

script:
    - export TZ=CET
    - export LD_LIBRARY_PATH=/usr/local/lib
    - autoreconf --install
    - ./configure --without-pth-test
    - make && cd test && make check && sudo make install
