name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get pthsem
      run: wget https://www.auto.tuwien.ac.at/~mkoegler/debian/pool/main/p/pthsem/pthsem_2.0.8.tar.gz
    - name: extract pthsem
      run: tar -zxf pthsem_2.0.8.tar.gz
    - name: build pthsem
      working-directory: pthsem-2.0.8
      run: ./configure && make && sudo make install
    - name: configure
      working-directory: ../
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
